Wire creator contracts
knownorigin/known-origin-subgraph pull request #110
Opened 2022-09-08 08:47 UTC by vince0656

https://github.com/knownorigin/known-origin-discovery/issues/1067

2022-10-20 09:05 UTC, jamesmorgan commented on abis/kodav4/BatchCreatorContract.json
> +[
Wondering if these names should be specific to the actual impl?

2022-10-20 09:05 UTC, jamesmorgan commented on abis/kodav4/CreatorFactory.json
> +[
Same for this in terms of file naming?

2022-10-20 09:55 UTC, jamesmorgan commented on abis/kodav4/SelfSovereignFundsHandler.json
> +[
Do we need this vs using the existing funds handlers?

2022-10-20 10:18 UTC, jamesmorgan requested changes

2022-10-20 10:18 UTC, jamesmorgan commented on schema.graphql
> +    defaultFundsRecipients: [Bytes!]!
Should this be a `Collective`?

2022-10-20 10:18 UTC, jamesmorgan commented on src/mappings/creator-contracts/creator-contract.ts
> +    editionEntity.save()
This needs an activity event I think

2022-10-20 10:18 UTC, jamesmorgan commented on src/mappings/creator-contracts/creator-contract.ts
> +    editionEntity.save()
Activity event

2022-10-20 10:18 UTC, jamesmorgan commented on src/mappings/creator-contracts/creator-contract.ts
> +    entity.save();
Activity event

2022-10-20 10:18 UTC, jamesmorgan commented on src/mappings/creator-contracts/creator-contract.ts
> +    entity.save();
Activity event

2022-10-20 10:18 UTC, jamesmorgan commented on src/mappings/creator-contracts/creator-contract.ts
> +    edition.save()
Activity event

2022-10-20 10:18 UTC, jamesmorgan commented on src/mappings/creator-contracts/creator-contract.ts
> +    edition.save()
Activity event

2022-10-20 10:18 UTC, jamesmorgan commented on src/mappings/creator-contracts/creator-contract.ts
> +    creatorContractEntity.save()
Activity event

2022-10-20 10:18 UTC, jamesmorgan commented on src/mappings/creator-contracts/creator-contract.ts
> +    creatorContractEntity.save()
Activity event

2022-10-20 10:18 UTC, jamesmorgan commented on src/mappings/creator-contracts/creator-contract.ts
> +    }
Activity event

2022-10-20 10:18 UTC, jamesmorgan commented on src/mappings/creator-contracts/creator-contract.ts
> +}
Activity event

2022-10-20 10:18 UTC, jamesmorgan commented on src/mappings/creator-contracts/creator-contract.ts
> +    tokenEntity.save()
Activity event

2022-10-20 10:18 UTC, jamesmorgan commented on src/mappings/creator-contracts/creator-contract.ts
> +    tokenEntity.save();
Activity event

2022-10-20 10:18 UTC, jamesmorgan commented on src/mappings/creator-contracts/creator-contract.ts
> +    listedEntity.save();
Activity event

2022-10-20 10:18 UTC, jamesmorgan commented on src/mappings/creator-contracts/creator-contract.ts
> +    );
Activity event

2022-10-20 10:18 UTC, jamesmorgan commented on src/mappings/creator-contracts/creator-contract.ts
> +}
All looks good but I think we need activity events for all events in which we will need to update marketplace state. We in essence scrap events and then use this to build a model of the editions/tokens. So any changes to these need an event I think

2022-10-20 10:18 UTC, jamesmorgan commented on src/mappings/creator-contracts/factory.ts
> +    artistEntity.save()
Activity event

2022-10-20 10:18 UTC, jamesmorgan commented on src/mappings/creator-contracts/factory.ts
> +    creatorContractEntity.save()
Activity event

2022-11-13 08:47 UTC, jamesmorgan requested changes
Looking good - some minor points

2022-11-13 08:47 UTC, jamesmorgan commented on abis/kodav4/ClaimableFundsReceiverV1.json
> +[
Do we need this - I think the assumption should be that funds handlers will be the V3 deployed flow for now so I dont think we need this ABI or logic in here atm

2022-11-13 08:47 UTC, jamesmorgan commented on src/services/ActivityEvent.service.ts
> +    return "CreatorContract"
Lets make this a constant for `"CreatorContract"`

2022-11-13 08:47 UTC, jamesmorgan commented on src/services/ActivityEvent.service.ts
> +    event.type = edition ? TYPE_EDITION : "CreatorContract" // For V4, we're either dealing with an edition or something at the global contract level
Constant

2022-11-13 08:47 UTC, jamesmorgan commented on schema.graphql
> +    creatorContract: Bytes # Optionally capture creator contract address if it is version 4
Could these be object mappings? `CreatorContract` and not `Bytes`?

2022-11-13 08:47 UTC, jamesmorgan commented on schema.graphql
> +    creatorContract: Bytes # Optionally capture creator contract address if this is version 4
Could these be object mappings? `CreatorContract` and not `Bytes`?

2022-11-13 08:47 UTC, jamesmorgan commented on schema.graphql
> +    creatorContract: Bytes # address of creator contract that minted the edition if version 4
Could these be object mappings? `CreatorContract` and not `Bytes`?

2022-11-13 08:47 UTC, jamesmorgan commented on schema.graphql
> +    secondaryRoyaltyV4EditionOverride: BigInt # At the edition level, the EIP2981 percentage requested by the creator(s)
Is this not the same as `artistCommission` ?

2022-11-13 08:47 UTC, jamesmorgan commented on schema.graphql
> +    deploymentTimestamp: BigInt!
Common deployment properties used on other entities 

```
    # Common event details
    timestamp: BigInt!
    transactionHash: Bytes!
    transactionIndex: BigInt!
    logIndex: BigInt!
    eventAddress: Bytes!
    eventTxFrom: Bytes!
    eventTxTo: Bytes
    blockNumber: BigInt!
```

Port over the ones which make sense and use same names if possible

2022-11-13 08:47 UTC, jamesmorgan commented on src/mappings/creator-contracts/creator-contract.ts
> +import {Address, BigDecimal, BigInt, Bytes, log, store} from "@graphprotocol/graph-ts";
Wondering if this should within the `v4` folder and not `creator-contracts` for consistancy?

2022-11-13 08:47 UTC, jamesmorgan commented on src/mappings/creator-contracts/creator-contract.ts
> +    let entityId = event.params._tokenId.toString() + '-' + event.address.toHexString();
I think we should have a common utils file/method which takes an ID and address and builds the composite key - prevents any issues arising form doing it in the wrong way some like this `buildCCKey(id, address)`

2022-11-13 08:47 UTC, jamesmorgan commented on src/mappings/creator-contracts/creator-contract.ts
> +    let entityId = event.params._tokenId.toString() + '-' + event.address.toHexString();
Common key

2022-11-13 08:47 UTC, jamesmorgan commented on src/mappings/creator-contracts/creator-contract.ts
> +    let entityId = event.params._tokenId.toString() + '-' + event.address.toHexString();
Common key

2022-11-13 08:52 UTC, jamesmorgan commented on src/services/Token.service.ts
> +    let entityId = tokenId.toString() + "-" + contractAddress.toHexString()
For some reason I would have assumed the other way round would be better `address-tokenId` as this is where the natural grouping lies - should be change?

2022-11-15 09:02 UTC, jamesmorgan commented on abis/kodav4/ClaimableFundsReceiverV1.json
> +[
Keep it - I was more thinking that the ABI is wrong not the logic i.e. should it be the V3 claimable funds receiver?

2022-11-15 09:03 UTC, jamesmorgan commented on src/services/Token.service.ts
> +    let entityId = tokenId.toString() + "-" + contractAddress.toHexString()
I think liam already did this yesterday but worth pulling and checking

2022-11-15 09:31 UTC, liamcf44 approved these changes

2022-11-16 10:20 UTC, jamesmorgan requested changes
LGTM - minor comment on burns

2023-01-16 13:32 UTC, jamesmorgan approved these changes

2023-01-20 08:48 UTC, merged