add ccEditionsCount
knownorigin/known-origin-subgraph pull request #149
Opened 2023-03-09 16:41 UTC by mattt-w

editionsCount contains both shared contract editions (v1,v2,v3) and creator contract editions (v4)

Create a new artist field called ccEditionsCount to count v4 editions

Use existing editionsCount field to count v1,v2,v3 editions

2023-03-10 08:40 UTC, jamesmorgan requested changes

2023-03-10 08:40 UTC, jamesmorgan commented on src/services/Artist.service.ts
> +export function addEditionToArtist(artistAddress: Address, editionNumber: string, totalAvailable: BigInt, created: BigInt, version: string): Artist {
Is this kodaVersion - if so we have some constants to pass in to the function to make it clearer. `KodaVersions.ts`

2023-03-10 08:40 UTC, jamesmorgan commented on src/services/Artist.service.ts
> +        artist.ccEditionsCount = artist.ccEditionsCount.plus(ONE)
`editionsCount` is used in other services as a data point - need to work out if we still want to split this IMO

One option is we keep `editionsCount` as the total count and then have a separate count for just CC?

2023-03-10 11:27 UTC, mattt-w commented on src/services/Artist.service.ts
> +export function addEditionToArtist(artistAddress: Address, editionNumber: string, totalAvailable: BigInt, created: BigInt, version: string): Artist {
changed to consts in KodaVersions.ts

2023-03-10 11:30 UTC, mattt-w commented on src/services/Artist.service.ts
> +        artist.ccEditionsCount = artist.ccEditionsCount.plus(ONE)
Agree that splitting `editionsCount` could affect other services.

Have made `editionsCount` the total edition amount and `ccEditionsCount` the total edition amount deployed on creator contracts

Can just subtract `ccEditionsCount from editionsCount` on the front end to get split counts

2023-03-14 10:12 UTC, jamesmorgan approved these changes

2023-03-17 10:42 UTC, merged